### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by msaron** [lanetix/react-jwt-store#16]
I looked at the documentation and was not sure on how to use it in my application. Once I run `userStore.init()`, does it automatically request a JWT from the web server? If so, how does it know what the server address is? 

Thanks.

**Comment by sandbochs** [comment]
The library assumes that the JWT is stored on a cookie under the key, `XSRF-TOKEN`. This can be overridden by passing cookie on the options hash:
```
  let userStore = require('react-jwt-store')({ cookie: 'NOT-XSRF-TOKEN'});
```
